import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');

test('督導檢視顯示所選案場整月全員班表，排班編輯維持不變',async()=>{
  const[app,css,html]=await Promise.all([read('assets/app.js'),read('assets/app.css'),read('index.html')]);
  assert.match(app,/id="scheduleEditView">排班編輯/);
  assert.match(app,/id="scheduleSupervisorView">督導檢視/);
  assert.match(app,/function renderSupervisorScheduleMonth/);
  assert.match(app,/function mobileStaffSupervisorOverview/);
  assert.match(app,/scheduleSupervisorScope:'site'/);
  assert.match(app,/id="supervisorMobileScope">機動人員全部案場/);
  assert.match(app,/employment_type==='mobile'/);
  assert.match(app,/當月份全部執勤人員/);
  assert.match(app,/整月唯讀檢視/);
  assert.doesNotMatch(app,/id="supervisorScheduleDate"/);
  assert.match(app,/renderSiteScheduleHalf/);
  assert.match(app,/saveSiteMonthlySchedule/);
  assert.match(css,/\.supervisor-month-table/);
  assert.match(css,/\.supervisor-mobile-hint/);
  assert.match(css,/\.supervisor-month-cell b\{font-size:14px\}/);
  assert.match(app,/scheduleDisplay==='edit'\?`<button class="btn ghost" id="printSiteSchedule"/);
  assert.match(css,/\.supervisor-month-cell/);
  assert.match(css,/\.supervisor-scope-switch/);
  assert.match(css,/\.mobile-staff-site/);
  assert.match(html,/assets\/app\.js\?v=122/);
  assert.match(css,/\.quote-type-options/);
  assert.match(html,/assets\/app\.css\?v=73/);
});

test('正式報價單提供大型用印區並抑制瀏覽器列印網址頁尾',async()=>{
  const[quotes,html]=await Promise.all([read('assets/tender-quotes.js'),read('index.html')]);
  assert.match(quotes,/function quoteDocument/);
  assert.match(quotes,/@page\{size:A4 portrait;margin:0\}/);
  assert.match(quotes,/紘嘉物業集團用印/);
  assert.match(quotes,/客戶／管委會用印/);
  assert.match(quotes,/公司用印處/);
  assert.match(quotes,/客戶用印處/);
  assert.match(quotes,/聯絡人姓名/);
  assert.match(quotes,/聯絡人電話/);
  assert.match(quotes,/function quoteContact/);
  assert.match(quotes,/letter-spacing:14px/);
  assert.match(quotes,/\.quote-title b\{justify-self:end;font-size:15px/);
  assert.match(quotes,/\.quote-title\{display:grid;grid-template-columns:300px 1fr/);
  assert.match(quotes,/\.quote-title h1\{width:300px;margin:0;text-align:center/);
  assert.match(quotes,/\.totals td\{border:0/);
  assert.match(quotes,/\.quote-head\{display:grid;grid-template-columns:300px 1fr;align-items:center\}/);
  assert.match(quotes,/\.quote-logos\{display:grid;grid-template-columns:1fr 1fr/);
  assert.match(quotes,/application\/msword/);
  assert.match(quotes,/data-t-download/);
  assert.match(quotes,/hongjia-property-full-logo\.png/);
  assert.match(quotes,/hongjia-security-knight-logo\.png/);
  assert.match(quotes,/taxRows=showTax\?/);
  assert.match(quotes,/<table class="totals">\$\{taxRows\}/);
  assert.match(quotes,/innerHTML=mode==='tax_excluded'\?/);
  assert.doesNotMatch(quotes,/\.delete\(\).*tender_quotation_items/);
  assert.match(quotes,/id="tenderAddTax"/);
  assert.match(quotes,/加計 5% 營業稅/);
  assert.match(quotes,/tax_excluded':'tax_exempt/);
  assert.doesNotMatch(quotes,/課稅方式<select/);
  assert.match(quotes,/quoteTypeNames=\['常駐','臨駐','增哨'\]/);
  assert.match(quotes,/class="quote-type-options wide"/);
  assert.match(quotes,/name="quote_type" type="checkbox"/);
  assert.match(quotes,/types=quoteTypes\(row\)/);
  assert.match(quotes,/types\.includes\(name\)/);
  assert.doesNotMatch(quotes,/type===name/);
  assert.match(html,/assets\/tender-quotes\.js\?v=19/);
});
