(()=>{'use strict';const client=window.ERP_CLIENT,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),monthNow=()=>new Date().toISOString().slice(0,7);let access,site,month=monthNow(),logs=[];const shifts={day:'日',night:'夜',mobile:'機',special:'特',cash:'現',custom:'班',off:'休',annual:'特休',personal:'事假',sick:'病假'};
$('#app').style.display='none';new MutationObserver(()=>{if(!$('#app').hidden){$('#app').style.display='block';$('#login').style.display='none'}}).observe($('#app'),{attributes:true,attributeFilter:['hidden']});
async function enter(){const{data,error}=await client.from('community_committee_access').select('*,sites(*)').eq('is_active',true).maybeSingle();if(error)throw error;if(!data)throw Error('此 Email 尚未由 ERP 指派社區權限');access=data;site=data.sites;$('#login').hidden=true;$('#app').hidden=false;$('#role').textContent=`${access.member_name} · ${access.committee_role}`;$('#siteName').textContent=site.name;$('#welcome').textContent=`${access.member_name}，您好`;$('#month').value=$('#logMonth').value=month;$('#siteInfo').innerHTML=`<div class="item"><strong>${esc(site.name)}</strong><small>${esc(site.address||'尚未登記地址')}</small></div><div class="item"><strong>社區聯絡</strong><small>${esc(site.community_phone||'—')}　｜　統編 ${esc(site.community_tax_id||'—')}</small></div><div class="item"><strong>帳號授權</strong><small>本帳號僅限 ${esc(site.name)}，社區由 ERP 管理者指定</small></div>`;await Promise.all([loadSchedule(),loadLogs(),loadItems()])}
async function loadSchedule(){const start=`${month}-01`,end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10),days=Number(end.slice(8)),{data,error}=await client.from('schedules').select('*,employees(full_name,employee_no)').eq('site_id',site.id).gte('work_date',start).lte('work_date',end).order('work_date');if(error)throw error;$('#scheduleCount').textContent=data?.length||0;const people=new Map;(data||[]).forEach(row=>{if(!people.has(row.employee_id))people.set(row.employee_id,{employee:row.employees,days:{}});people.get(row.employee_id).days[Number(row.work_date.slice(8))]=row});$('#scheduleTable').innerHTML=people.size?`<table><thead><tr><th>姓名</th>${Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join('')}</tr></thead><tbody>${[...people.values()].map(p=>`<tr><td>${esc(p.employee?.full_name||'—')}</td>${Array.from({length:days},(_,i)=>{const row=p.days[i+1];return`<td>${row?`<span class="shift">${esc(shifts[row.shift_type]||row.work_time_text||'班')}</span>`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table>`:'<div class="card">本月尚無排班資料</div>'}
async function loadLogs(){const start=`${month}-01`,end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10),{data,error}=await client.from('community_work_logs').select('*,employees(full_name,job_title)').eq('site_id',site.id).gte('log_date',start).lte('log_date',end).eq('visible_to_committee',true).order('log_date',{ascending:false});if(error)throw error;logs=data||[];for(const row of logs)if(row.attachment_path){const{data:signed}=await client.storage.from('community-work-log-media').createSignedUrl(row.attachment_path,900);row.attachment_url=signed?.signedUrl||''}$('#logCount').textContent=logs.length;renderLogs('#latestLogs',logs.slice(0,5));renderLogs('#logList',logs)}
function renderLogs(selector,rows){const status={completed:'已完成',processing:'處理中',pending:'待處理'},category={general:'一般行政',administration:'行政文書',finance:'財務作業',repair:'修繕設備',vendor:'廠商聯繫',resident:'住戶服務',meeting:'會議事項',incident:'異常事件',other:'其他'};$(selector).innerHTML=rows.length?rows.map(row=>`<article class="${selector==='#logList'?'log-card':'item'}"><div class="meta">${esc(row.log_date)} · ${esc(row.employees?.job_title||'')} ${esc(row.employees?.full_name||'')}</div><h3>${esc(row.title)}</h3><span class="badge">${esc(category[row.category]||row.category)} · ${esc(status[row.follow_up_status]||row.follow_up_status)}</span><p>${esc(row.content)}</p>${row.attachment_url?`<a href="${row.attachment_url}" target="_blank"><img class="work-log-photo" src="${row.attachment_url}" alt="工作日誌照片"></a>`:''}</article>`).join(''):'<div class="item">目前沒有工作日誌</div>'}
async function loadItems(){const{data,error}=await client.from('community_committee_items').select('*').eq('site_id',site.id).order('created_at',{ascending:false});if(error){$('#itemList').innerHTML='<div class="item">建議事項功能尚未完成資料庫更新</div>';return}const labels={suggestion:'委員建議事項',reminder:'提醒事項'},statuses={new:'待處理',processing:'處理中',completed:'已完成'};$('#pendingCount').textContent=(data||[]).filter(x=>x.status!=='completed').length;$('#itemList').innerHTML=data?.length?data.map(x=>`<div class="item"><strong>${esc(labels[x.item_type])}｜${esc(x.title)}</strong><small>${new Date(x.created_at).toLocaleString('zh-TW')}｜${esc(statuses[x.status])}</small><p>${esc(x.content)}</p></div>`).join(''):'<div class="item">目前沒有建議或提醒事項</div>'}
$('#committeeItemForm').onsubmit=async e=>{e.preventDefault();const m=$('#itemMessage'),row=Object.fromEntries(new FormData(e.currentTarget));row.site_id=site.id;row.access_id=access.id;m.textContent='正在送出…';const{error}=await client.from('community_committee_items').insert(row);if(error){m.textContent=`送出失敗：${error.message}`;return}e.currentTarget.reset();m.textContent='已送出，ERP 管理者可以立即查看。';await loadItems()};
const sendPasswordMail=email=>client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});let timer;function cooldown(seconds=60){const b=$('#resetPassword');clearInterval(timer);let n=seconds;b.disabled=true;timer=setInterval(()=>{b.textContent=`請等待 ${n--} 秒後重寄`;if(n<0){clearInterval(timer);b.disabled=false;b.textContent='忘記密碼／重寄設定信'}},1000)}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,m=$('#loginMessage');m.textContent='登入中…';const{error}=await client.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(error){m.textContent='登入失敗：Email 或密碼錯誤；首次使用請開啟 ERP 寄出的設定信。';return}try{await enter()}catch(x){await client.auth.signOut();m.textContent=x.message}};
$('#signup').onclick=async()=>{$('#loginMessage').textContent='帳號必須由 ERP 管理者建立並指定社區；請使用收到的設定信建立密碼。'};$('#resetPassword').onclick=async()=>{const email=$('#loginForm').email.value.trim(),m=$('#loginMessage');if(!email){m.textContent='請先輸入 ERP 授權 Email';return}const{error}=await sendPasswordMail(email);m.textContent=error?`設定信寄送失敗：${error.message}`:'設定信已寄出，請查看收件匣及垃圾郵件。';cooldown(60)};
function showPasswordSetup(){const panel=$('#passwordSetup');panel.hidden=false;panel.style.display='grid';$('#login').hidden=true;$('#login').style.display='none';setTimeout(()=>panel.querySelector('input')?.focus(),100)}
$('#passwordSetupForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,message=$('#passwordSetupMessage'),password=form.password.value,confirmation=form.confirm_password.value;if(password.length<8){message.textContent='密碼至少需要 8 碼';return}if(password!==confirmation){message.textContent='兩次輸入的密碼不同';return}const button=form.querySelector('button');button.disabled=true;message.textContent='正在儲存…';const{error}=await client.auth.updateUser({password});if(error){message.textContent=`設定失敗：${error.message}`;button.disabled=false;return}message.textContent='密碼設定完成，正在返回登入畫面…';await client.auth.signOut();setTimeout(()=>location.href=location.pathname,700)};
client.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'||event==='INVITED')showPasswordSetup()});
$('#logout').onclick=async()=>{await client.auth.signOut();location.reload()};document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===button.dataset.view))});$('#month').onchange=async e=>{month=e.target.value;$('#logMonth').value=month;await Promise.all([loadSchedule(),loadLogs()])};$('#logMonth').onchange=async e=>{month=e.target.value;$('#month').value=month;await Promise.all([loadSchedule(),loadLogs()])};client.auth.getSession().then(({data})=>{if(data.session)enter().catch(async e=>{await client.auth.signOut();$('#loginMessage').textContent=e.message})});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
})();
