(()=>{'use strict';const client=window.ERP_CLIENT,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),monthNow=()=>new Date().toISOString().slice(0,7);let access,site,month=monthNow(),logs=[];const shifts={day:'日',night:'夜',mobile:'機',special:'特',cash:'現',custom:'班',off:'休',annual:'特休',personal:'事假',sick:'病假'};
$('#app').style.display='none';
new MutationObserver(()=>{if(!$('#app').hidden){$('#app').style.display='block';$('#login').style.display='none'}}).observe($('#app'),{attributes:true,attributeFilter:['hidden']});
async function enter(){const{data,error}=await client.from('community_committee_access').select('*,sites(*)').eq('is_active',true).order('created_at').limit(1).maybeSingle();if(error)throw error;if(!data)throw Error('此 Email 尚未由 ERP 指派社區權限');access=data;site=data.sites;$('#login').hidden=true;$('#app').hidden=false;$('#role').textContent=`${access.member_name} · ${access.committee_role}`;$('#siteName').textContent=site.name;$('#welcome').textContent=`${access.member_name}，您好`;$('#month').value=$('#logMonth').value=month;$('#siteInfo').innerHTML=`<div class="item"><strong>${esc(site.name)}</strong><small>${esc(site.address||'尚未登記地址')}</small></div><div class="item"><strong>社區聯絡</strong><small>${esc(site.community_phone||'—')}　｜　統編 ${esc(site.community_tax_id||'—')}</small></div><div class="item"><strong>合約期間</strong><small>${esc(site.contract_start_date||'—')} 至 ${esc(site.contract_end_date||'—')}</small></div>`;await Promise.all([loadSchedule(),loadLogs()])}
async function loadSchedule(){const start=`${month}-01`,end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10),days=Number(end.slice(8)),{data,error}=await client.from('schedules').select('*,employees(full_name,employee_no)').eq('site_id',site.id).gte('work_date',start).lte('work_date',end).order('work_date');if(error)throw error;$('#scheduleCount').textContent=data?.length||0;const people=new Map;(data||[]).forEach(row=>{const key=row.employee_id;if(!people.has(key))people.set(key,{employee:row.employees,days:{}});people.get(key).days[Number(row.work_date.slice(8))]=row});const head=Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join(''),body=[...people.values()].map(p=>`<tr><td>${esc(p.employee?.full_name||'—')}</td>${Array.from({length:days},(_,i)=>{const row=p.days[i+1];return`<td>${row?`<span class="shift">${esc(shifts[row.shift_type]||row.work_time_text||'班')}</span>`:'—'}</td>`}).join('')}</tr>`).join('');$('#scheduleTable').innerHTML=people.size?`<table><thead><tr><th>姓名</th>${head}</tr></thead><tbody>${body}</tbody></table>`:'<div class="card">本月尚無排班資料</div>'}
async function loadLogs(){const start=`${month}-01`,end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10),{data,error}=await client.from('community_work_logs').select('*,employees(full_name,job_title)').eq('site_id',site.id).gte('log_date',start).lte('log_date',end).eq('visible_to_committee',true).order('log_date',{ascending:false});if(error)throw error;logs=data||[];$('#logCount').textContent=logs.length;$('#pendingCount').textContent=logs.filter(x=>x.follow_up_status!=='completed').length;renderLogs('#latestLogs',logs.slice(0,5));renderLogs('#logList',logs)}
function renderLogs(selector,rows){const status={completed:'已完成',processing:'處理中',pending:'待處理'},category={general:'一般行政',administration:'行政文書',finance:'財務作業',repair:'修繕設備',vendor:'廠商聯繫',resident:'住戶服務',meeting:'會議事項',incident:'異常事件',other:'其他'};$(selector).innerHTML=rows.length?rows.map(row=>`<article class="${selector==='#logList'?'log-card':'item'}"><div class="meta">${esc(row.log_date)} · ${esc(row.employees?.job_title||'')} ${esc(row.employees?.full_name||'')}</div><h3>${esc(row.title)}</h3><span class="badge">${esc(category[row.category]||row.category)} · ${esc(status[row.follow_up_status]||row.follow_up_status)}</span><p>${esc(row.content)}</p></article>`).join(''):'<div class="item">目前沒有工作日誌</div>'}
const sendPasswordMail=async email=>client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});
let mailCooldownTimer;
function startMailCooldown(seconds=60){const button=$('#resetPassword');clearInterval(mailCooldownTimer);let remain=Math.max(1,Number(seconds)||60);button.disabled=true;const render=()=>button.textContent=`請等待 ${remain} 秒後重寄`;render();mailCooldownTimer=setInterval(()=>{remain-=1;if(remain<=0){clearInterval(mailCooldownTimer);button.disabled=false;button.textContent='忘記密碼／重寄設定信';return}render()},1000)}
function cooldownSeconds(message){const matched=String(message||'').match(/after\s+(\d+)\s+seconds?/i);return matched?Number(matched[1]):0}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,m=$('#loginMessage');m.textContent='登入中…';const{error}=await client.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(error){m.textContent='登入失敗：Email 或密碼錯誤；若是首次使用或忘記密碼，請按下方重寄設定信。';return}try{await enter()}catch(x){await client.auth.signOut();m.textContent=x.message}};
$('#signup').onclick=async()=>{const f=$('#loginForm'),m=$('#loginMessage'),email=f.email.value.trim(),password=f.password.value;if(!email||password.length<8){m.textContent='請先輸入 ERP 授權 Email 與至少 8 碼密碼';return}m.textContent='正在建立帳號…';const{data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}${location.pathname}`}});if(error){m.textContent=`建立失敗：${error.message}`;return}if(!data.user?.identities?.length){const{error:mailError}=await sendPasswordMail(email);m.textContent=mailError?`此 Email 已有帳號，但設定信寄送失敗：${mailError.message}`:'此 Email 已有登入帳號，已寄送密碼設定信。請查看收件匣及垃圾郵件。';return}m.textContent='驗證信已寄出。請點擊 Email 內的驗證連結，再回到此頁登入。'};
$('#resetPassword').onclick=async()=>{const f=$('#loginForm'),m=$('#loginMessage'),email=f.email.value.trim(),button=$('#resetPassword');if(!email){m.textContent='請先輸入 ERP 授權的 Email';return}button.disabled=true;m.textContent='正在寄送設定信…';const{error}=await sendPasswordMail(email);if(error){const seconds=cooldownSeconds(error.message);if(seconds){m.textContent=`為保護帳號安全，請等待 ${seconds} 秒後再重寄設定信。`;startMailCooldown(seconds)}else{button.disabled=false;m.textContent=`設定信寄送失敗：${error.message}`}return}m.textContent='密碼設定信已寄出，請查看收件匣及垃圾郵件。';startMailCooldown(60)};
client.auth.onAuthStateChange(async event=>{if(event!=='PASSWORD_RECOVERY')return;const password=prompt('請設定新的登入密碼（至少 8 碼）');if(!password||password.length<8){$('#loginMessage').textContent='密碼尚未變更，請再次開啟設定信並輸入至少 8 碼密碼。';return}const{error}=await client.auth.updateUser({password});if(error){$('#loginMessage').textContent=`密碼設定失敗：${error.message}`;return}alert('密碼設定完成，現在可以使用新密碼登入。');await client.auth.signOut();location.href=location.pathname});
$('#logout').onclick=async()=>{await client.auth.signOut();location.reload()};document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===button.dataset.view))});$('#month').onchange=async e=>{month=e.target.value;$('#logMonth').value=month;await Promise.all([loadSchedule(),loadLogs()])};$('#logMonth').onchange=async e=>{month=e.target.value;$('#month').value=month;await Promise.all([loadSchedule(),loadLogs()])};client.auth.getSession().then(({data})=>{if(data.session)enter().catch(async e=>{await client.auth.signOut();$('#loginMessage').textContent=e.message})});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
})();
